<a href="https://colab.research.google.com/github/tomatox/action-tutorial/blob/main/mytest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

torch.__version__


'2.3.1+cu121'

In [ ]:
x = torch.empty(4, 2)
print(x)

tensor([[8.4951e+20, 2.6393e-09],
        [2.1707e-18, 1.6678e+19],
        [7.0976e+22, 2.1715e-18],
        [3.0135e+29, 1.7610e+19]])


In [ ]:
x = torch.rand(4, 2)
print(x)

tensor([[0.4791, 0.8921],
        [0.9416, 0.8520],
        [0.3290, 0.1845],
        [0.5365, 0.9374]])


In [ ]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [ ]:
x = torch.tensor([3.,2,3])
print(x)

tensor([3., 2., 3.])


In [ ]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.2476, -0.4038, -1.0681, -0.3704],
        [ 0.3167, -1.0763,  0.8601,  0.5242]])


In [ ]:
x.size()

NameError: name 'x' is not defined

In [ ]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
print(ft.short())

tensor([1, 2, 3], dtype=torch.int16)


In [ ]:
print(ft.int())

tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)
print(it.float())
print(it.long())

tensor([1, 2, 3], dtype=torch.int32)
torch.int32
tensor([1., 2., 3.])
tensor([1, 2, 3])


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.2839])
-0.28393837809562683
torch.float32


In [ ]:
import torch
x = torch.randn(1)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cpu
tensor([1.])
tensor([0.3772])
tensor([1.3772])
tensor([1.3772], dtype=torch.float64)


In [ ]:
import torch

t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)


3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
import math
a = torch.rand(1,2)
print(a)

tensor([[0.8854, 0.2997]])


In [ ]:
import torch
import math

a = torch.rand(1,2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))

tensor([[0.7423, 0.2432]])
tensor([[0.7423, 0.2432]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.5000, 0.2432]])
tensor(0.2432)
tensor(0.7423)
tensor(0.4928)
tensor(0.3529)
tensor(0.1805)
tensor([1, 2, 3])


In [ ]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.4318, 0.0980],
        [0.6110, 0.6719]])
torch.return_types.max(
values=tensor([0.6110, 0.6719]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.4318, 0.6719]),
indices=tensor([0, 1]))


In [ ]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)
print(x+y)
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[0.2038, 0.6684],
        [0.4939, 0.8191]])
tensor([[0.8745, 0.3796],
        [0.4489, 0.0150]])
tensor([[1.0783, 1.0479],
        [0.9428, 0.8342]])
tensor([[1.0783, 1.0479],
        [0.9428, 0.8342]])


In [ ]:
import torch
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x)
print(x/y)
print(torch.matmul(x, y))
print(x.matmul(y))

tensor([[0.3249, 0.7912],
        [0.3743, 0.0805]])
tensor([[0.7415, 0.4851],
        [0.8503, 0.6407]])
tensor([[0.3046, 0.6199],
        [0.3057, 0.1116]])
tensor([[1.3154, 0.9852],
        [0.4977, 0.5358]])
tensor([[1.3154, 0.9852],
        [0.4977, 0.5358]])


In [ ]:
x = torch.Tensor([[1,2],[3,4]])

print(x)
print(x[0,1])
print(x[1,1])
print(x.view)

tensor([[1., 2.],
        [3., 4.]])
tensor(2.)
tensor(4.)


In [ ]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = x.view(5, -1)
print(z)

tensor([[-0.0788, -0.5684,  0.7143, -1.1479,  0.1747],
        [ 0.7185,  0.4521, -0.2190, -0.1188,  0.0125],
        [ 1.9434,  0.5022,  1.3680, -0.6876,  0.7603],
        [ 2.4773, -1.3345, -0.0455, -1.1690,  0.3736]])
tensor([-0.0788, -0.5684,  0.7143, -1.1479,  0.1747,  0.7185,  0.4521, -0.2190,
        -0.1188,  0.0125,  1.9434,  0.5022,  1.3680, -0.6876,  0.7603,  2.4773,
        -1.3345, -0.0455, -1.1690,  0.3736])
tensor([[-0.0788, -0.5684,  0.7143, -1.1479],
        [ 0.1747,  0.7185,  0.4521, -0.2190],
        [-0.1188,  0.0125,  1.9434,  0.5022],
        [ 1.3680, -0.6876,  0.7603,  2.4773],
        [-1.3345, -0.0455, -1.1690,  0.3736]])


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.0117])
0.011738608591258526
torch.float32


In [ ]:
tensor = torch.randn(1,3, 3)
print(tensor)
print(tensor.shape)
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[[-0.1919, -1.2124, -0.2923],
         [-1.1582,  0.8375,  0.5500],
         [ 0.4198,  0.1345,  0.2259]]])
torch.Size([1, 3, 3])
tensor([[-0.1919, -1.2124, -0.2923],
        [-1.1582,  0.8375,  0.5500],
        [ 0.4198,  0.1345,  0.2259]])
torch.Size([3, 3])


In [ ]:
t = torch.randn(3, 3)
print(t)
print(t.shape)

tensor([[-0.0947, -0.7069,  0.4429],
        [ 1.2230,  0.0943, -0.5733],
        [-0.7452, -1.6973, -0.5298]])
torch.Size([3, 3])


In [ ]:
tensor = t.unsqueeze(dim=2)
print(t)
print(t.shape)

tensor([[-0.0947, -0.7069,  0.4429],
        [ 1.2230,  0.0943, -0.5733],
        [-0.7452, -1.6973, -0.5298]])
torch.Size([3, 3])


In [ ]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2, 5])
print(y)
z = torch.FloatTensor([3, 6])
print(z)
print(torch.stack([x, y, z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
a = torch.randn(1,3, 3)
print(a)
b = torch.randn(1,3, 3)
print(b)
c = torch.cat((a, b), dim=0)
print(c)
print(c.size())

tensor([[[-0.6902,  1.3321,  0.5784],
         [-0.5002,  1.7513, -1.2663],
         [ 0.1987, -1.6068,  0.4255]]])
tensor([[[ 0.7770,  1.4157, -1.5048],
         [-0.3627,  0.8450, -1.3524],
         [ 0.3161, -0.8743,  0.5678]]])
tensor([[[-0.6902,  1.3321,  0.5784],
         [-0.5002,  1.7513, -1.2663],
         [ 0.1987, -1.6068,  0.4255]],

        [[ 0.7770,  1.4157, -1.5048],
         [-0.3627,  0.8450, -1.3524],
         [ 0.3161, -0.8743,  0.5678]]])
torch.Size([2, 3, 3])


In [ ]:
import torch

t = torch.rand(3,6)
print(t)
t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.6662, 0.4672, 0.2426, 0.0997, 0.0319, 0.0351],
        [0.6375, 0.0887, 0.2755, 0.5937, 0.5363, 0.0464],
        [0.3568, 0.5946, 0.6344, 0.5464, 0.1240, 0.7880]])
tensor([[0.6662, 0.4672],
        [0.6375, 0.0887],
        [0.3568, 0.5946]])
tensor([[0.2426, 0.0997],
        [0.2755, 0.5937],
        [0.6344, 0.5464]])
tensor([[0.0319, 0.0351],
        [0.5363, 0.0464],
        [0.1240, 0.7880]])


In [ ]:
t = torch.rand(3,6)
t1, t2 = torch.split(t, 3, dim=1)
print(t)
print(t1)
print(t2)

tensor([[0.4035, 0.2112, 0.1815, 0.2687, 0.1159, 0.7454],
        [0.1833, 0.8023, 0.2555, 0.4437, 0.0175, 0.5202],
        [0.5270, 0.9009, 0.0355, 0.2410, 0.6036, 0.5097]])
tensor([[0.4035, 0.2112, 0.1815],
        [0.1833, 0.8023, 0.2555],
        [0.5270, 0.9009, 0.0355]])
tensor([[0.2687, 0.1159, 0.7454],
        [0.4437, 0.0175, 0.5202],
        [0.2410, 0.6036, 0.5097]])


In [ ]:
a = torch.ones(7)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)


tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.])


In [ ]:
import numpy as np, torch
a = np.ones(7)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


array([2., 2., 2., 2., 2., 2., 2.])

In [ ]:
import torch
a = torch.rand(3,3)
print(a)
a = a * 3
print(a, a.requires_grad)
a.requires_grad_(True)
#print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor([[0.5334, 0.5217, 0.2175],
        [0.8406, 0.0757, 0.7441],
        [0.4340, 0.7975, 0.6413]])
tensor([[1.6002, 1.5652, 0.6524],
        [2.5218, 0.2271, 2.2323],
        [1.3020, 2.3925, 1.9238]]) False
tensor(27.9507, grad_fn=<SumBackward0>)


In [ ]:
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [ ]:
y = x + 5
print(y)

z = y * y
out = z.mean()
print(z, out)

print(out)
out.backward()
#print(out)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)
tensor(36., grad_fn=<MeanBackward0>)


In [ ]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [ ]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([ 1501.9797, -1255.1791,   200.1699], grad_fn=<MulBackward0>)


In [ ]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
#y.backward(v)
#print(x.grad)

In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)



True
True


In [ ]:

import torch
a = torch.ones(2,2, requires_grad=True)
print(a.data)
print(a.grad)
print(a.grad_fn)
b = a + 2
c = b ** 2
print(c)
out = c.sum()
print(out)
out.backward()

tensor([[1., 1.],
        [1., 1.]])
None
None
tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)
tensor(36., grad_fn=<SumBackward0>)


In [ ]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [ ]:
print(b.data)
print(b.grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


<ipython-input-11-7222c1aec66c>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(b.grad)


In [ ]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


<ipython-input-12-f6ca42a4f63f>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(c.grad)


In [ ]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


<ipython-input-14-85e75c577388>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(out.grad)
